CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    password_algorithm VARCHAR(32) NOT NULL DEFAULT 'bcrypt',
    role VARCHAR(255) NOT NULL DEFAULT 'Security Analyst',
    company VARCHAR(255) NOT NULL DEFAULT 'Independent Research',
    location VARCHAR(255) NOT NULL DEFAULT 'Hyderabad, India',
    focus_area VARCHAR(255) NOT NULL DEFAULT 'OSINT & Metadata Analysis',
    bio TEXT,
    website VARCHAR(512) NOT NULL DEFAULT '',
    headline VARCHAR(255) NOT NULL DEFAULT 'Security analyst building practical cyber workflows.',
    profile_picture MEDIUMTEXT,
    facebook_url VARCHAR(512) NOT NULL DEFAULT '',
    instagram_url VARCHAR(512) NOT NULL DEFAULT '',
    linkedin_url VARCHAR(512) NOT NULL DEFAULT '',
    tiktok_url VARCHAR(512) NOT NULL DEFAULT '',
    x_url VARCHAR(512) NOT NULL DEFAULT '',
    youtube_url VARCHAR(512) NOT NULL DEFAULT '',
    show_profile_to_logged_in_users TINYINT(1) NOT NULL DEFAULT 1,
    show_activity_on_profile TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
)
